# Generated by Django 6.0.6 on 2026-07-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('Hardware', 'Hardware'), ('Software', 'Software'), ('Network', 'Network'), ('Account', 'Account'), ('Email', 'Email'), ('Security', 'Security'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
